name: Build frp Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: '0'
      - name: Setup Go environment
        uses: actions/setup-go@main
        with:
          go-version: 1.21
          check-latest: true
      - run: go version

      - uses: msys2/setup-msys2@main
        with:
          install: >-
            coreutils
            curl
            diffutils
            gawk
            gcc
            make
      - name: Compile frp
        run: make

      - name: Rename Artifacts
        run: |
              cd bin/
              mv frpc frpc.exe
              mv frps frps.exe
      - name: Upload Artifacts of frpc and frps
        uses: actions/upload-artifact@main
        with:
          name: frp_win
          path: bin/
