name: Build frp Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # environment
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: '0'
      - name: Setup Go environment
        uses: actions/setup-go@main
        with:
          go-version: 1.21
          check-latest: true
      - run: go version

      - uses: msys2/setup-msys2@dist
        with:
          install: >-
            coreutils
            curl
            diffutils
            gawk
            gcc
            make
      - name: Compile frp
        run: make

      - name: Rename Artifacts
        run: |
              cd bin/
              mv frpc frpc.exe
              mv frps frps.exe

      - name: Release frp Windows
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "frp_win"
          automatic_release_tag: "build_frp"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "bin/"
          prerelease: false
